### ISSUE TITLE
Eintrag bei Wahl des Netzwerktyps für LTE auf Englisch statt Deutsch

### ISSUE THREAD

**Issue by markFreak** [berlinux2016/MIUI13#1]
- **MIUI Version:** 22.2.9
- **Device name:** Redmi K40 Pro

**Screenshot/Description:**
![Screenshot_2022-02-13-14-52-58-964_com android phone](https://user-images.githubusercontent.com/99874868/154451920-494ff627-4ff8-4815-bd92-1ad9b92fa0f0.jpg)
Seit dem Stable Release von MIUI 13 Anfang Januar gibt es diesen Übersetzungs-Bug (siehe Screenshot), hat sich in den darauffolgenden Weeklies nicht geändert.

**Comment by Henry2o1o** [comment]
wurde vor 5 Monaten geändert
![image](https://user-images.githubusercontent.com/6131799/154520637-4799227f-4195-4f84-8ea9-fdf9db19d95c.png)

**Comment by markFreak** [comment]
Well, obviously that specific string entry regarding LTE has not been applied.  Maybe because somewhere else there is a string named "preferred_network_type_pref_entries_lte_preferred", but is not translated, and the code
points to that un-translated string. Changing the language to Spanish shows the same bug
![Screenshot_2022-02-17-17-44-35-971_com android phone](https://user-images.githubusercontent.com/99874868/154531812-c6dfd92e-5d42-41fa-8e8c-d642ae0bd557.jpg)
:

**Comment by markFreak** [comment]
We have 22.10.26, and still not solved.

**Comment by berlinux2016** [comment]
It's solved in the new miui dev branch - Android 13 (not old weekly).

**Comment by markFreak** [comment]
Ah, okay, thx.

**Comment by berlinux2016** [comment]
Last Fixed with today push in MIUI 14 branch
