### ISSUE TITLE
Aufgabencenter Wenn/Dann vertauscht

### ISSUE THREAD

**Issue by lpetflo** [berlinux2016/MIUI13#3]
- **MIUI Version:** 22.4.29
- **Device name:** Mi 11 Ultra

**Screenshot/Description:**

Ich habe einen kleinen Bug im Aufgabencenter (Akku/Akku/Automatisierte Aufgaben) bemerkt. Bei den einzelnen Aufgaben ist Wenn/Dann jeweils genau falsch herum übersetzt. Kein großes Ding aber wäre schön, das demnächst zu korrigieren.

EDIT: Wenn man eine Aufgabe zu "Meine  Aufgaben" kopiert passt die Zuordnung witzigerweise.

![Screenshot_2022-05-07-19-18-47-969_com miui securitycenter](https://user-images.githubusercontent.com/33376496/167265114-62b18963-815d-4744-b3ad-6c1b39629ad5.png)

**Comment by Henry2o1o** [comment]
<string name="auto_task_default_do_action">Wenn</string>
    <string name="auto_task_default_if_exclude">Dann</string>
    
    <string name="auto_task_default_do_action">Then</string>
    <string name="auto_task_default_if_exclude">If</string>
    
👍

**Comment by lpetflo** [comment]
Super, danke!
