### ISSUE TITLE
Xiaomi 12 can't connect to the car

### ISSUE THREAD

**Issue by muugie** [berlinux2016/MIUI13#9]
Hi,
when I try to connect my phone via usb c cable, it does not connect to the car.
I have set default USB configuration to File Transfer but when plug in the usb c cable,
I see that the phone tries to connect but connection is not established. MI 11 and MI 9
have no problems. I have installed latest stable V13.0.36.0.
From peply in forum I see I am not the only one with this problem

**Comment by MeiGuddet** [comment]
@muugie Das hat nichts mit der deutschen Übersetzung zu tun. Bitte diskutiere dein Problem im zuständigen Forum.
